### ISSUE TITLE
Retry strategy masks all compiler bugs

### ISSUE THREAD

**Issue by jack-melchert** [StanfordAHA/aha#1915]
Hey Steve, the retry strategy implemented in garnet.py and regress.py:
https://github.com/StanfordAHA/aha/blob/251bd0e5b6418bfc5a20180dd8f45563c5964334/aha/util/regress.py#L49
will mask any compiler failures. Because we call the compiler stages using subprocess, any error will be caught as a `subprocess.CalledProcessError`, and since there is no else statement to the `if 'SIGSEGV' in str(e):`, any error won't be caught, and the regression will just continue on. 

We probably want an `else: raise Exception("Exception in mapping/garnet")` or something like that.

**Comment by jack-melchert** [comment]
https://github.com/StanfordAHA/aha/blob/master/aha/aha.py#L58
https://github.com/StanfordAHA/aha/blob/master/aha/util/garnet.py#L20
https://github.com/StanfordAHA/aha/blob/master/aha/util/regress.py#L49

I think these are the three places that need to be fixed.

**Comment by steveri** [comment]
Oops yes there was definitely suppsed to be an "else raise exception", i could have sworn i had included it.
Arg.
I will fix, thanks very much for calling it out.

**Comment by steveri** [comment]
Oops yes there was definitely suppsed to be an "else raise exception", i could have sworn i had included it.
Arg.
I will fix, thanks very much for calling it out.

**Comment by steveri** [comment]
Fixed, see https://github.com/StanfordAHA/aha/pull/1916
