### ISSUE TITLE
Cannot run the quickstart on kiwi?

### ISSUE THREAD

**Issue by dillonhuff** [StanfordAHA/aha#638]
Hey @hofstee I'm trying to run the quick start described in the docs on kiwi, but I get the following error:

```bash
dhuff@kiwi:~/aha$ pip install -e .
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/dhuff/aha
ERROR: Package 'aha' requires a different Python: 3.6.9 not in '>=3.7'
```

Any idea what I'm doing wrong?

**Comment by hofstee** [comment]
You should probably create a virtual environment. I think you can do that with `python -m virtualenv -p python3.7 .` on kiwi, then `source bin/activate` to activate it.

**Comment by dillonhuff** [comment]
Worked like a charm. Thanks!
